sudo: required
language: python
services:
  - docker

before_install:
  - docker pull saltstack/centos-7-minimal
script:
  - docker run -v $(pwd):/srv saltstack/centos-7-minimal /bin/sh -c "ls -l /srv && cp /srv/salt/etc/minion.vagrant /etc/salt/minion && yum install -y python-pip && cd /srv/ && pip install -r requirements.txt && pytest -v"
