sudo: required
language: python
services:
  - docker

before_install:
  - docker pull saltstack/centos-7-minimal
  - docker run -d saltstack/centos-7-minimal -v .:/salt -v ./salt/etc:/etc/salt/ /bin/sh -c "echo in; ls -l"
  - docker run -d saltstack/centos-7-minimal -v .:/salt -v ./salt/etc:/etc/salt/ /bin/sh -c "cd /salt/; pip install -r requirements.txt"
script: pytest
