sudo: required
language: python
services:
  - docker

before_install:
  - docker pull saltstack/centos-7-minimal
  - ls -l
  - docker run -d saltstack/centos-7-minimal /bin/sh -c "echo in; ls -l"
script: pytest
