version: '3'
services:
  master:
    build:
      context: .
      dockerfile: templates/docker/dockerfile-master
    volumes:
    - .:/srv
    expose:
    - "4505"
    - "4506"
    hostname: master
  minion_dev:
    build:
      context: .
      dockerfile: templates/docker/dockerfile-minion
    hostname: minion-dev-int
    links:
    - master
  masterless:
    build:
      context: .
      dockerfile: templates/docker/dockerfile-masterlessminion
    hostname: minion
    volumes:
    - .:/srv
